feat: Output Run ID
bugbug-io/bugbug-github-action pull request #2
Opened 2024-05-17 16:35 UTC by jhkersul

## Why? :thinking:

Hello! For my test scenario, I need to have access to the `suiteRunId` or `testRunId` to generate a link for the test executed. So I added two new possible outputs: `suiteRunId` and `testRunId` 

## How? :technologist:

- Capturing the execution output on a variable and checking if has `suiteRunId` or `testRunId`
- Sending values to the [$GITHUB_OUTPUT](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-masking-a-generated-output-within-a-single-job) variable

## Result 🔢 

- You can access on

2024-05-21 06:30 UTC, simplypixi commented
Hi @jhkersul !
First of all, thank you for the PR. <3 

The code seems to be fine in general :)
I left you one small comment.

2024-05-21 07:00 UTC, simplypixi requested changes

2024-05-21 07:00 UTC, simplypixi commented on README.md
> +          echo "Suite Run ID: ${{ steps.run-bugbug-tests.outputs.suiteRunId }} | Test Run ID: ${{ steps.run-bugbug-tests.outputs.testRunId }}"
Could you split this into two echo commands?

2024-05-21 07:41 UTC, simplypixi commented
@jhkersul I wonder if I might ask you another question, apart from the PR. Do you really need those outputs? You run specific suite/test using this gh-action, so you have direct access to suiteId/testId.

I think it's a good idea to return some extra data as action output, but I'm just wondering whether there's a particular reason you need those outputs.

2024-05-22 18:46 UTC, jhkersul commented
> @jhkersul I wonder if I might ask you another question, apart from the PR. Do you really need those outputs? You run specific suite/test using this gh-action, so you have direct access to suiteId/testId.
> 
> I think it's a good idea to return some extra data as action output, but I'm just wondering whether there's a particular reason you need those outputs.

I do have access to the `suiteId/testId`, but I don't have access to the `suiteRunId` and `testRunId` 🤔 

My use case: I run my E2E Tests during PR phase, and after the tests run, I comment on the PR with the result of the test, with a link to the report (this link needs the Run ID)

Example:
<img width="506" alt="image" src="https://github.com/bugbug-io/bugbug-github-action/assets/1427347/1da5264b-5034-41e9-bbcf-1bfd2a85d5e7">

The link is like:
`https://app.bugbug.io/organizations/<ORG_ID>/projects/<PROJECT_ID>/runs-history/suites/${suiteRunId}/`

2024-05-22 18:54 UTC, jhkersul commented on README.md
> +          echo "Suite Run ID: ${{ steps.run-bugbug-tests.outputs.suiteRunId }} | Test Run ID: ${{ steps.run-bugbug-tests.outputs.testRunId }}"
Done here 👍

2024-05-23 07:50 UTC, simplypixi commented
> > @jhkersul I wonder if I might ask you another question, apart from the PR. Do you really need those outputs? You run specific suite/test using this gh-action, so you have direct access to suiteId/testId.
> > I think it's a good idea to return some extra data as action output, but I'm just wondering whether there's a particular reason you need those outputs.
> 
> I do have access to the `suiteId/testId`, but I don't have access to the `suiteRunId` and `testRunId` 🤔

Oh, that's right. Sorry for the misunderstanding. 😅 

> My use case: I run my E2E Tests during PR phase, and after the tests run, I comment on the PR with the result of the test, with a link to the report (this link needs the Run ID)
> 

Sounds like a great idea for a new optional feature to implement directly in the action 👍

2024-05-23 07:51 UTC, simplypixi commented on README.md
> +          echo "Suite Run ID: ${{ steps.run-bugbug-tests.outputs.suiteRunId }} | Test Run ID: ${{ steps.run-bugbug-tests.outputs.testRunId }}"
Great 🥳

2024-05-23 07:51 UTC, simplypixi approved these changes

2024-05-23 07:52 UTC, merged